apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/vjkancherla
    chart: petclinic
    # see - https://argo-cd.readthedocs.io/en/stable/user-guide/tracking_strategies/#helm
    targetRevision: "0.1.*"
    # No helm values needed - chart already has correct image
  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic-dev
  syncPolicy:
    automated:
      prune: true        # Enable auto-pruning of resources no longer in Git
      selfHeal: true     # Enable auto-healing when cluster state drifts from Git
      allowEmpty: false  # Prevent sync if no resources would be applied
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground  # Ensure proper cleanup order
      - PruneLast=true                     # Prune resources after sync is complete
    retry:
      limit: 5           # Retry failed syncs up to 5 times
      backoff:
        duration: 5s     # Initial retry delay
        factor: 2        # Exponential backoff factor
        maxDuration: 3m  # Maximum retry delay